#!/usr/bin/env ruby
require_relative 'boot'

db_config = {
  name: 'romsample_dev',
  user: 'romsample',
  password: 'romsample',
  port: 5432,
  encoding: 'utf8'
}

config = ROM::Configuration.new(:sql, 'postgres://localhost:5432/romsample_dev', db_config)
config.register_relation(Companies, Posts)

MAIN_CONTAINER = ROM.container(config)

Pry.start